version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: myapp_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - /mnt/docker_volumes/myapp/postgres/data:/var/lib/postgresql/data
      - /mnt/docker_volumes/myapp/postgres/logs:/var/log/postgresql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: myapp_redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - /mnt/docker_volumes/myapp/redis/data:/data
      - /mnt/docker_volumes/myapp/redis/logs:/var/log/redis
    restart: unless-stopped
